# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cac33571f945c86c0ab8f5fa61e28ca751c8b8419bc149d53680e45cf284fdc29379c9f8c5104c2b0686ad90ada2f56ce1cfdaa02eca9e4836dc844a5a4e058

test:
  secret_key_base: d3411a437675db158d5fc7a3db459cb5583474f7d8a3b37c112884c1a933c3cdac7675278502a00d13f175c0f7e93ecf102243b04142d79e09b45d0dec7cf3e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
